// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "GPG En- and Decryption.",
    "title": "gpg",
    "version": "1.0",
    "x-direktiv-meta": {
      "categories": [
        "tools",
        "security"
      ],
      "container": "gcr.io/direktiv/apps/gpg",
      "issues": "https://github.com/direktiv-apps/gpg/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "This function provides GPG to Direktiv. There are minor differences using it in a container, e.g. decryption needs\nthe following additional parameters ` + "`" + `--pinentry-mode loopback` + "`" + ` and ` + "`" + `--batch` + "`" + `.",
      "maintainer": "[direktiv.io](https://www.direktiv.io)",
      "url": "https://github.com/direktiv-apps/gpg"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "commands": {
                  "description": "Array of commands.",
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "command": {
                        "description": "Command to run",
                        "type": "string",
                        "example": "gpg --list-keys"
                      },
                      "continue": {
                        "description": "Stops excecution if command fails, otherwise proceeds with next command",
                        "type": "boolean"
                      },
                      "print": {
                        "description": "If set to false the command will not print the full command with arguments to logs.",
                        "type": "boolean",
                        "default": true
                      },
                      "silent": {
                        "description": "If set to false the command will not print output to logs.",
                        "type": "boolean",
                        "default": false
                      }
                    }
                  }
                },
                "files": {
                  "description": "Files are getting created before running commands.",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/direktivFile"
                  }
                },
                "private": {
                  "description": "Base64-encoded private GPG key. If not set ` + "`" + `private.key` + "`" + ` file will be used.",
                  "type": "string"
                },
                "public": {
                  "description": "Base64-encoded public GPG key. If not set ` + "`" + `public.key` + "`" + ` file will be used.",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Results of command array.",
            "schema": {
              "type": "object",
              "properties": {
                "gpg": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": [
                      "success",
                      "result"
                    ],
                    "properties": {
                      "result": {
                        "additionalProperties": false
                      },
                      "success": {
                        "type": "boolean"
                      }
                    }
                  }
                }
              }
            },
            "examples": {
              "gpg": {
                "gpg": [
                  {
                    "result": "pub   rsa3072 2022-03-23 [SC] [expires: 2024-03-22]\n      A0FD12334AA0777FB47D05854B687F9FBAC356A3\nuid           [ unknown] DirektivTestKey \u003cinfo@direktiv.io\u003e\nsub   rsa3072 2022-03-23 [E] [expires: 2024-03-22]",
                    "success": true
                  }
                ]
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "exec",
              "continue": false,
              "exec": "/bin/runner"
            },
            {
              "action": "exec",
              "exec": "{{- if (empty .Public) }}\necho \"no public key in request\"\n{{- else }}\nbash -c 'echo {{ .Public }} | base64 --decode \u003e {{ .DirektivDir }}/public.key'\n{{- end }}",
              "print": false,
              "silent": true
            },
            {
              "action": "exec",
              "exec": "{{- if (empty .Private) }}\necho \"no private key in request\"\n{{- else }}\nbash -c 'echo {{ .Private }} | base64 --decode \u003e {{ .DirektivDir }}/private.key'\n{{- end }}",
              "print": false,
              "silent": true
            },
            {
              "action": "exec",
              "exec": "gpg --batch --import {{ .DirektivDir }}/private.key"
            },
            {
              "action": "exec",
              "continue": false,
              "exec": "gpg --batch --import {{ .DirektivDir }}/public.key"
            },
            {
              "action": "foreach",
              "continue": "{{ .Item.Continue }}",
              "env": [
                "ENV GPG_TTY=/dev/console"
              ],
              "exec": "{{ .Item.Command }}",
              "loop": ".Commands",
              "print": "{{ .Item.Print }}",
              "silent": "{{ .Item.Silent }}"
            }
          ],
          "output": "{\n  \"gpg\": {{ index . 5 | toJson }}\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: req\n     type: action\n      action:\n        function: gpg\n        secrets: [\"private-key.asc\", \"gpg-pwd\"]\n        files:\n        - key: public-key.asc\n          scope: namespace\n          as: public.key\n        input: \n          private: jq(.secrets.\"private-key.asc\")\n          commands: \n          - command: gpg --pinentry-mode loopback --passphrase jq(.secrets.\"gpg-pwd\") -v --output pgp.tar.gz --batch --decrypt pgp.tar.gz.pgp",
            "title": "Decrypting"
          },
          {
            "content": "- id: req\n     type: action\n      action:\n        function: gpg\n        secrets: [\"private-key.asc\", \"gpg-pwd\"]\n        files:\n        - key: public-key.asc\n          scope: namespace\n          as: public.key\n        input: \n          private: jq(.secrets.\"private-key.asc\")\n          commands: \n          - command: gpg --output out/namespace/jq(.name).tar.gz.gpg --trust-model always --batch -r A0FD12334AA0777FB47D05854B687F9FBAC356A3 --encrypt file.tar.gz",
            "title": "Encrypting"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: gpg\n    image: gcr.io/direktiv/apps/gpg:1.0\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "GPG En- and Decryption.",
    "title": "gpg",
    "version": "1.0",
    "x-direktiv-meta": {
      "categories": [
        "tools",
        "security"
      ],
      "container": "gcr.io/direktiv/apps/gpg",
      "issues": "https://github.com/direktiv-apps/gpg/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "This function provides GPG to Direktiv. There are minor differences using it in a container, e.g. decryption needs\nthe following additional parameters ` + "`" + `--pinentry-mode loopback` + "`" + ` and ` + "`" + `--batch` + "`" + `.",
      "maintainer": "[direktiv.io](https://www.direktiv.io)",
      "url": "https://github.com/direktiv-apps/gpg"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "commands": {
                  "description": "Array of commands.",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CommandsItems0"
                  }
                },
                "files": {
                  "description": "Files are getting created before running commands.",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/direktivFile"
                  }
                },
                "private": {
                  "description": "Base64-encoded private GPG key. If not set ` + "`" + `private.key` + "`" + ` file will be used.",
                  "type": "string"
                },
                "public": {
                  "description": "Base64-encoded public GPG key. If not set ` + "`" + `public.key` + "`" + ` file will be used.",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Results of command array.",
            "schema": {
              "type": "object",
              "properties": {
                "gpg": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/GpgItems0"
                  }
                }
              }
            },
            "examples": {
              "gpg": {
                "gpg": [
                  {
                    "result": "pub   rsa3072 2022-03-23 [SC] [expires: 2024-03-22]\n      A0FD12334AA0777FB47D05854B687F9FBAC356A3\nuid           [ unknown] DirektivTestKey \u003cinfo@direktiv.io\u003e\nsub   rsa3072 2022-03-23 [E] [expires: 2024-03-22]",
                    "success": true
                  }
                ]
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "exec",
              "continue": false,
              "exec": "/bin/runner"
            },
            {
              "action": "exec",
              "exec": "{{- if (empty .Public) }}\necho \"no public key in request\"\n{{- else }}\nbash -c 'echo {{ .Public }} | base64 --decode \u003e {{ .DirektivDir }}/public.key'\n{{- end }}",
              "print": false,
              "silent": true
            },
            {
              "action": "exec",
              "exec": "{{- if (empty .Private) }}\necho \"no private key in request\"\n{{- else }}\nbash -c 'echo {{ .Private }} | base64 --decode \u003e {{ .DirektivDir }}/private.key'\n{{- end }}",
              "print": false,
              "silent": true
            },
            {
              "action": "exec",
              "exec": "gpg --batch --import {{ .DirektivDir }}/private.key"
            },
            {
              "action": "exec",
              "continue": false,
              "exec": "gpg --batch --import {{ .DirektivDir }}/public.key"
            },
            {
              "action": "foreach",
              "continue": "{{ .Item.Continue }}",
              "env": [
                "ENV GPG_TTY=/dev/console"
              ],
              "exec": "{{ .Item.Command }}",
              "loop": ".Commands",
              "print": "{{ .Item.Print }}",
              "silent": "{{ .Item.Silent }}"
            }
          ],
          "output": "{\n  \"gpg\": {{ index . 5 | toJson }}\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: req\n     type: action\n      action:\n        function: gpg\n        secrets: [\"private-key.asc\", \"gpg-pwd\"]\n        files:\n        - key: public-key.asc\n          scope: namespace\n          as: public.key\n        input: \n          private: jq(.secrets.\"private-key.asc\")\n          commands: \n          - command: gpg --pinentry-mode loopback --passphrase jq(.secrets.\"gpg-pwd\") -v --output pgp.tar.gz --batch --decrypt pgp.tar.gz.pgp",
            "title": "Decrypting"
          },
          {
            "content": "- id: req\n     type: action\n      action:\n        function: gpg\n        secrets: [\"private-key.asc\", \"gpg-pwd\"]\n        files:\n        - key: public-key.asc\n          scope: namespace\n          as: public.key\n        input: \n          private: jq(.secrets.\"private-key.asc\")\n          commands: \n          - command: gpg --output out/namespace/jq(.name).tar.gz.gpg --trust-model always --batch -r A0FD12334AA0777FB47D05854B687F9FBAC356A3 --encrypt file.tar.gz",
            "title": "Encrypting"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: gpg\n    image: gcr.io/direktiv/apps/gpg:1.0\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "CommandsItems0": {
      "type": "object",
      "properties": {
        "command": {
          "description": "Command to run",
          "type": "string",
          "example": "gpg --list-keys"
        },
        "continue": {
          "description": "Stops excecution if command fails, otherwise proceeds with next command",
          "type": "boolean"
        },
        "print": {
          "description": "If set to false the command will not print the full command with arguments to logs.",
          "type": "boolean",
          "default": true
        },
        "silent": {
          "description": "If set to false the command will not print output to logs.",
          "type": "boolean",
          "default": false
        }
      }
    },
    "GpgItems0": {
      "type": "object",
      "required": [
        "success",
        "result"
      ],
      "properties": {
        "result": {
          "additionalProperties": false
        },
        "success": {
          "type": "boolean"
        }
      }
    },
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
}
